### ISSUE TITLE
Moving all the test files to folders

### ISSUE THREAD

**Issue by MatanP12** [redhat-beyond/ResuMe#104]
Moving all the test files in each module to a folder to organize the code files

getting this error:
![image](https://user-images.githubusercontent.com/36789773/163704379-e69de492-d3ff-433b-9f81-ffd698bdf9b1.png)

**Comment by MatanP12** [comment]
@TomerNewmanPrograms Takes care of this in #105

**Comment by TomerNewmanPrograms** [comment]
> Moving all the test files in each module to a folder to organize the code files
> 
> getting this error: ![image](https://user-images.githubusercontent.com/36789773/163704379-e69de492-d3ff-433b-9f81-ffd698bdf9b1.png)

This happened to me also, I changed `test.py` to `test_posts.py` in posts/tests and it works now. #94
