### ISSUE TITLE
Changing users passwords

### ISSUE THREAD

**Issue by yulisuliman** [redhat-beyond/ResuMe#134]
Change user’s password to more easier and memorable passwords

**Comment by natifridman** [comment]
Can you elaborate on this issue? what is the issue?

**Comment by yulisuliman** [comment]
> Can you elaborate on this issue? what is the issue?

The current user’s passwords are random and not memorable.
We wanted to change the passwords to easier ones in order to ease the process of logging in to different users for our tests.
